### ISSUE TITLE
Items get stacked when loaded using ajax

### ISSUE THREAD

**Issue by rico** [shershen08/vue-masonry#1]
I'm having a problem that the items get stacked, when added from ajax call. I guess I would need to trigger the method to layout  the items again. Can I somehow access the masonry instance and trigger `reloadItems()` after receiving the items from ajax call?

**Comment by shershen08** [comment]
@rico thanks for the report,

Do you have the correct markup int your templates?
```
<div v-masonry ...
    <div v-masonry-tile v-for="(item, index) in blocks"...
```
and then the `blocks` array is being increased after the ajax call succeeds?

Anyway I'll take a look and try to reproduce the issue and get back with fixes tonight. I already had some related improvements in progress.

**Comment by rico** [comment]
@shershen08 - I did indeed miss the `v-masonry-tile` directive. Didn't pay close enough attention cause I set the `item-selector` for the `v-masonry` directive to the exact same element and didn't notice the tile directive. So - now it works! Thanks!

**Comment by tetreault** [comment]
Hello, I'm having a similar issue. The plugin is working as expected if all the project tiles share the same dimensions, however on one of our sites I have a design where `.project-tile-container:nth-of-type(1)` needs to be 100% width, and then the rest should stack into two columns underneath it. 

What is currently happening is the first project tile is 100% width as expected, and then the rest stack in one single column all the way down the page. Having some issues figuring out why that is happening. If it isn't too much trouble, I can share my usage @rico @shershen08 

work.vue page: 
```
<template>
  <section class="work container">
    <NavBar/>
      <div class="case-study-container">
        <div v-masonry transition-duration="0.6s" fit-width="true" origin-left="true" origin-top="true" item-selector=".item" class="masonry-container">
          <ProjectTile
            v-for="(item, index) in homePageData"
            :key="index"
            :project-title="item.projectTitle"
            :projectAsset="item.asset"
            :client-link="item.clientLink"
            :client-name="item.clientName"
            :align-class="item.alignClass"
            :project-emotion="item.projectEmotion"
            :case-study="item.caseStudy"
          />
        </div>
      </div>
  </section>
</template>

<script>
import NavBar from '~/components/navbar/navbar.vue';
import ProjectTile from '~/components/project-tile/project-tile.vue';
import homePageData from '~/static/data/home-page-data.js';

export default {
  data() {
    return {
      homePageData
    };
  },
  components: {
    NavBar,
    ProjectTile
  }
}
</script>
<style>
.case-study-container {
  width: inherit;
  height: 100vh;
  display: block;
  overflow-x: hidden;
  margin-top: 60px;
}
.masonry-container {
  width: inherit;
  margin: 0 auto;
}
</style>
```

project-tile.vue component: 
```
<template>
  <no-ssr>
    <div v-masonry-tile class="project-tile-container item" :class="alignClass">
      <div class="project-image-container">
        <nuxt-link class="case-study-link" :to="caseStudy">
          <img :src="projectAsset">
        </nuxt-link>
      </div>
      <div class="project-text" :class="alignClass">
        <p>{{ projectTitle }}</p>
        <p v-if="clientName">Client: <a :href="clientLink" target="_blank" :title="clientName">{{ clientName }}</a></p>
        <p>Emotion: {{ projectEmotion }}</p>
      </div>
    </div>
  </no-ssr>
</template>

<script>
export default {
  props: ['projectTitle', 'clientName', 'clientLink', 'projectAsset', 'alignClass', 'projectEmotion', 'caseStudy'],
  components: {}
}
</script>
<style>
  .project-tile-container {
    width: 35%;
    min-width: 250px;
    margin: 0 auto;
    padding: 15px;
    height: 35vh;
    min-height: 380px;
    margin: 0 0 1em;
    border: 1px solid white;
  }

/* make first instance take full width */
  .project-tile-container:nth-of-type(1) {
    width: 100%;
  }
  .project-image-container img {
    max-width: 400px;
    width: 50%;
    min-width: 250px;
  }
  @media (max-width: 500px) {
    .project-text { display: none; }
    .project-image-container img { min-width: 220px; }
  }
  @media (max-width: 320px) {
    .project-image-container img { min-width: 190px; }
  }
</style>
```

**Comment by tetreault** [comment]
More specifically, I see that after making my first instance of the project tile 100% width every subsequent tile (for some reason) gets  `left: 0px` and I'm not too sure why.

**Comment by tetreault** [comment]
I suspect the first full width element is affecting how masonry determines column width, and that I should render the full width item separately from the rest of the masonry items
