### ISSUE TITLE
Can we have category filter with the items in vue-masonry?

### ISSUE THREAD

**Issue by bhavinichauhan-easternts** [shershen08/vue-masonry#105]

**Comment by shershen08** [comment]
Thanks for your question @bhavinichauhan-easternts 
if I got you correctly - filter is a generic element that can be added to a list that you're displaying in vue-masonry or just to any list of items. So this is not a part of the plugin functionality.

closing as won't be implemented in the plugin;
feel free to re-open if you have any concerns
