### ISSUE TITLE
jsfiddle demo has console errors

### ISSUE THREAD

**Issue by bbecker-te** [shershen08/vue-masonry#106]
When I open the provided [jsfiddle](https://jsfiddle.net/jericopulvera/wq07brjs), I see these errors in the devTools console:
```
?editor_console=false:76 [Vue warn]: Failed to resolve directive: masonry-tile

(found in <Anonymous>)
error @ ?editor_console=false:76
?editor_console=false:76 [Vue warn]: Failed to resolve directive: masonry

(found in <Anonymous>)
```

**Comment by shershen08** [comment]
thanks for the note @bbecker-te 
updated the link to demo - https://jsfiddle.net/shershen08/n54039qg/
