### ISSUE TITLE
Version 0.12.0 published on NPM legitimate?

### ISSUE THREAD

**Issue by stayallive** [shershen08/vue-masonry#107]
I see there was a new version published on NPM but nothing here, is this package version legitimate?

From a quick diff I'm not noticing much worrying but I'm also not an expert in diffing minified code.

**Comment by shershen08** [comment]
Thanks for checking @stayallive 
indeed I published v 0.12.0 several days ago,
that one includes the conde added in this https://github.com/shershen08/vue-masonry/pull/95

**Comment by stayallive** [comment]
Perfect, thanks!
