### ISSUE TITLE
Please add changelog, tags and releases

### ISSUE THREAD

**Issue by skjnldsv** [shershen08/vue-masonry#108]
Hi,

It's pretty hard to see if there was any breaking changes and what changed between releases.
Would you consider filling github's release page as well as providing tags and changelog to this repo?

That would really help preventing regressions and knowing what happened over time :)

Thanks and take care! :v:  :hugs:

**Comment by shershen08** [comment]
Good suggestion @skjnldsv 
I've created a release for the latest version - https://github.com/shershen08/vue-masonry/releases/tag/0.12.0

I guess creating a changelog for previous versions that go back years back is time-consuming without much of added value.
but will try to follow the changelog in upcoming releases
