### ISSUE TITLE
upgrade vue-no-ssr to vue-client-only

### ISSUE THREAD

**Issue by cc2937** [shershen08/vue-masonry#109]
the origin `vue-no-ssr` has upgraded to `vue-client-only`

**Comment by shershen08** [comment]
thanks for the note @chanjsq I'll try to incorporate and test this one coming weeks

**Comment by shershen08** [comment]
added, https://github.com/shershen08/vue-masonry/commit/46888d824df38b3a0f54b20ed088d250c635990c
