### ISSUE TITLE
How can I use the gutter property in a good way using vue-masonry?

### ISSUE THREAD

**Issue by Frzurita** [shershen08/vue-masonry#11]

**Comment by Frzurita** [comment]
Hi! I'm using your npm package which works perfectly but I would like to know how can I set different properties using best practices.

Thanks!

**Comment by shershen08** [comment]
Hello @Frzurita  the gutter property is not yet currently supported. The supported list is in https://github.com/shershen08/vue-masonry/blob/master/README.md
I'll try to add gutter coming days.

**Comment by renatoslcdevshop** [comment]
Any workaround until then?

**Comment by shershen08** [comment]
I've just committed version 0.10.2 - it should be available there.
Let me know if it worked our well

**Comment by renatoslcdevshop** [comment]
Great! Many thanks.

I just noticed there's a bootstrap way to set it. Since I'm already using bootstrap, should I use that instead of manually setting the gutter? Any drawbacks in either approaches?

**Comment by shershen08** [comment]
@renatoslcdevshop passing gutter properties using only vue-masonry component can have 2 benefits, as I can see this:
 - you use consistently one way to configure your masonry layout
 - you (in case if needed) can dynamically change the gutter property from your JS/VUE
