### ISSUE TITLE
'$redrawVueMasonry' of null - Vuetify Integration 

### ISSUE THREAD

**Issue by kinger251285** [shershen08/vue-masonry#112]
Hi 

I have just downloaded the latest version via npm and trying to use vue-masonry in an existing project.

However i am getting the below console error: '$redrawVueMasonry' of null

The grid shows but it is overlapping my footer and the height of the row is not expanding with the content.

My Code below:

`<v-row v-masonry>
    <v-col v-for="(imageInfo, index) in images" :key="index" cols="12" sm="4">
      <v-card height="100%" color="transparent" class="pt-1 pb-1" tile flat>        
        <v-img :src="imageInfo.first_image[0].low_res_src" @load="this.$redrawVueMasonry()"></v-img>        
      </v-card>
    </v-col>
  </v-row>`

Thanks in advance.

**Comment by FlambeSk** [comment]
Consider use mansory ID too. 

<v-row v-masonry="'masonryGridId">

And then use @load="$redrawVueMasonry(masonryGridId)"

**Comment by shershen08** [comment]
Closing as no updates for a while.
Feel free to reopen if you have extra input.

**Comment by shershen08** [comment]
was the [FlambeSk](https://github.com/FlambeSk) comment helpful for you [kinger251285](https://github.com/kinger251285) ?
