### ISSUE TITLE
Add provider for Vue3 version, so redraw can be called in hooks

### ISSUE THREAD

**Issue by wbw** [shershen08/vue-masonry#115]
Consider adding a 'provider' (`app.provide`) for the redraw in the Vue3 version of the plugin, so it could be injected in the composition API during setup and thus used in lifecycle hooks (i.e. something like `const redraw = inject("redrawVueMasonry");`).

**Comment by shershen08** [comment]
will be adressed in #114

**Comment by shershen08** [comment]
here's the comment about the new version https://github.com/shershen08/vue-masonry/issues/114#issuecomment-965602562
let's followup there
