### ISSUE TITLE
Error Events.emit is not a function

### ISSUE THREAD

**Issue by rosenfeldalon** [shershen08/vue-masonry#121]
On version 0.14.0 using Vue 2 with TypeScript and composition API, 
when leaving component that uses vue-masonary gets the following error:

`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in directive masonry unbind hook: "TypeError: Events.emit is not a function"
`

**Comment by shershen08** [comment]
Currency library is in transition mode supporting both Vue version 2 in version 3.
However a composition API function is only available when you have version 3 explicitly used,

https://github.com/shershen08/vue-masonry/blob/93d83bb1230476d6f24b44c03e292e622ddc26da/src/masonry.plugin.js#L129

So the idea is you should not be using composition API functionality of vue-masonry with compatibility plugin on Vue 2

**Comment by rosenfeldalon** [comment]
Thanks for the quick reply, it seems that the error is caused on vue-masonry/src/masonry.plugin.js line 102
` Events.emit(`${EVENT_DESTROY}__${masonryId}`)`
in the unbind function, 

perhaps doing  the checks you've done checking if Vue2 will solve this error:
`Events[`${isVue2 ? '$' : ''}emit`](`${EVENT_ADD}__${masonryId}`)`

Regards,

**Comment by hollote** [comment]
Please take a look at PR https://github.com/shershen08/vue-masonry/pull/123

**Comment by shershen08** [comment]
merged, thanks

**Comment by seonwoo960000** [comment]
Is this fixed in version 0.14.0 ? I still see this error. Thanks in advance

**Comment by rosenfeldalon** [comment]
hey @shershen08 any thoughts on releasing a patch version with the fix? perhaps 14.1
will be much appreciated!

Regards,

**Comment by shershen08** [comment]
@rosenfeldalon published **0.14.1** just now - https://www.npmjs.com/package/vue-masonry

please upgrade and give it a try

**Comment by rosenfeldalon** [comment]
@shershen08 thanks! the version in npm is marked as 0.14.1 but the GitHub repo is still 0.14.0, when installing the issue still occurs...

**Comment by shershen08** [comment]
When instal the new version is the problem fixed?

**Comment by rosenfeldalon** [comment]
no, as I mentioned the fix is not included in the **masonry.plugin.js** file as shown in the PR for some reason
https://github.com/shershen08/vue-masonry/pull/123/files

this Is after removing node_modules before clean install

**Comment by rosenfeldalon** [comment]
@shershen08 perhaps there was something that went wrong in the merge, see attached screenshots, hope this will help clarify the situation:

![shershen08_vue-masonry__💠_Vue_js_directive_for_masonry_blocks_layouting_✅](https://user-images.githubusercontent.com/12997716/153142512-acb9f9a6-b97b-430e-88d7-95e9bccb471d.png)

![datomize-ui_–___Documents_datomize_projects_datomize-ui_node_modules_vue-masonry_src_masonry_plugin_js](https://user-images.githubusercontent.com/12997716/153143000-14a55eb0-8cf5-49e2-b123-5e56cebf33d1.png)

Regards,

**Comment by shershen08** [comment]
guys, will fix it today.

**Comment by shershen08** [comment]
@rosenfeldalon  @seonwoo960000 
i've just published 0.15.0
please check if that is OK now?
