### ISSUE TITLE
./node_modules/vue-demi/lib/index.mjs Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.mjs' 

### ISSUE THREAD

**Issue by Sirros** [shershen08/vue-masonry#126]
{
  "name": "hello-world",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "monaco-editor": "^0.31.1",
    "vue": "^2.6.11",
    "vue-masonry": "^0.14.1",
    "vue-monaco-editor": "^0.0.19",
    "vue-waterfall2": "^1.10.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "style-resources-loader": "^1.5.0",
    "vue-cli-plugin-style-resources-loader": "^0.1.5",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by damienroche** [comment]
@Sirros if you are using this plugin for Vue.js 2 I recommended to downgrade version to 0.12.0 in package.json

**Comment by Sirros** [comment]
@damienroche  ok, it worked, thanks
