### ISSUE TITLE
Error Unexpected character '`' in ver 0.11.8

### ISSUE THREAD

**Issue by hongdung6992** [shershen08/vue-masonry#127]
When I run `npm run build` in my Vuejs project
It show error

> ERROR in build.js from UglifyJs
Unexpected character '`' [./node_modules/vue-masonry/src/masonry.plugin.js:71,0][build.js:89997,20]

Not sure how or if it can be fixed?

**Comment by shershen08** [comment]
can you try to upgrade to `0.15.0` ?
