### ISSUE TITLE
integration problem with view3

### ISSUE THREAD

**Issue by guiguinational** [shershen08/vue-masonry#129]
I can't use the package with Vue3,
the file masonry-vue3.plugin.js doesn't exist,
instead there is the one for vue2 but I can't use it

**Comment by shershen08** [comment]
There's a `vue-masonry-plugin-umd.js` file that should work with Vue3
https://unpkg.com/browse/vue-masonry@0.15.0/dist/

**Comment by shershen08** [comment]
closing as no answer
