### ISSUE TITLE
Divider between items

### ISSUE THREAD

**Issue by Dropth** [shershen08/vue-masonry#13]
Hi !

First, thanks for this library. I install it and it works perfectly.

Nevertheless, I have a question. Can we add divider (like a line) between our items ? I didn't notice any reference about this in your doc.

Thanks in advance !

**Comment by shershen08** [comment]
Hello @Dropth please take a look at the readme and masonry options more carefully, I suppose **gutter** is what you meant to use - https://masonry.desandro.com/options.html#gutter
