### ISSUE TITLE
Issues with Vue 3

### ISSUE THREAD

**Issue by rubebop** [shershen08/vue-masonry#143]
Concerning the documentation and the usage with Vue 3 (vue-masonry version >= 0.14.0), the following is written:
> import { VueMasonryPlugin } from "vue-masonry/src/masonry-vue3.plugin";

First of all, I don't see any "masonry-vue3.plugin" file in the corresponding "node_modules" folder. What I can find is "masonry.plugin.js" file. If I run the start the app as indicated, I get the following error message:

`Module not found: Error: Can't resolve 'vue-masonry/src/masonry-vue3.plugin' in [...]`

If instead I change the import to
- `import { VueMasonryPlugin } from "vue-masonry/src/masonry.plugin";` or 
- `import { VueMasonryPlugin } from "vue-masonry";`, I get several error messages like this one:

`ERROR in ./node_modules/vue-masonry/node_modules/vue-demi/lib/index.mjs 5:11-14
export 'default' (imported as 'Vue') was not found`

Did someone make vue-masonry work in Vue 3? What am I missing? Is this project still alive?

**Comment by shershen08** [comment]
I will check and get back you @rubebop

**Comment by shershen08** [comment]
indeed the docs were incorrect, I fixed the readme, please try again @rubebop

**Comment by rubebop** [comment]
@shershen08 thanks a lot for your effort: it works now.
