### ISSUE TITLE
How to use with browserify?

### ISSUE THREAD

**Issue by satuweb** [shershen08/vue-masonry#17]
I use browserify and bebelify
trunk/node_modules/vue-masonry/index.js:1
>> import {VueMasonryPlugin} from './src/VueMasonry.vue'
>> ^
>> ParseError: 'import' and 'export' may appear only with 'sourceType: module'
Warning: Error running grunt-browserify. Use --force to continue.

Could you help me?

**Comment by shershen08** [comment]
This is not a bug of the lib, it's your tooling is not setup right. 

Try googling for this error text "ParseError: 'import' and 'export' may appear only with 'sourceType: module'", I am pretty sure you will find out what's missing.
