### ISSUE TITLE
[Vue warn]: Failed to resolve directive: masonry

### ISSUE THREAD

**Issue by nikkanetiya** [shershen08/vue-masonry#18]
I am using VueJS version "2.3.4" with web pack.

window.Vue = require('vue');
Vue.use(require('vue-masonry'));

it is not working for me it gives an error
`[Vue warn]: Failed to resolve directive: masonry`

Is there anything needs to change to work with web pack?

**Comment by shershen08** [comment]
It's probably because you are using webpack require for named imports in the vue-masonry module. 
Try call it like this - 
```
Vue.use(require('vue-masonry').VueMasonryPlugin);
```

**Comment by nikkanetiya** [comment]
it's working fine now. Thanks for the guidelines. 

Would Like to ask one more thing, will it work Vue.redrawVueMasonry()?

**Comment by shershen08** [comment]
@nikkanetiya yes that should work 

Closing the issue for now

**Comment by nikkanetiya** [comment]
Sure, Thanks.
