### ISSUE TITLE
block not visible in element-ui tabs 

### ISSUE THREAD

**Issue by kalidiagne** [shershen08/vue-masonry#19]
I'm using v-masonty with element-ui tabs.
if i switch in tabs the blocks are not visible.
but It's work when i resize the page, i think in caused by the initial height of the tab, indeed if i inspect the style i found that 
`style="position: relative; height: 0px;"` and then at resize `position: relative; height: 1091.11px;`

**Comment by shershen08** [comment]
hi @kalidiagne can you provide a demo of the problem?

**Comment by kalidiagne** [comment]
hi @shershen08 
you can see it there https://app.hyfy.io/v/abMB1KxNa0U/

**Comment by shershen08** [comment]
that seem the case for the masonry redraw call.
Did you try to add `Vue.redrawVueMasonry()` call when a tab is opened first or each time?

**Comment by kalidiagne** [comment]
hi @shershen08 im trying  with that code
`<el-tabs v-model="currentTab" @tab-click="test"> [...] </el-tabs>`

**Comment by shershen08** [comment]
I see, 
I'll try to reproduce it this week and see where's the problem lies

**Comment by iamwill123** [comment]
Hey @shershen08 I really appreciate your work on vue-masonry, and I just wanted to show my appreciate and support. I am going to create a "boilerplate" kind of thing that shows the usage of your module once I flush out my own blog app that utilizes your module. Thanks again and awesome work!

**Comment by iamwill123** [comment]
@kalidiagne Hey did you get it working? if you can get a fiddle up, we can totally get to debugging it

**Comment by mikeevstropov** [comment]
There are no solutions?

**Comment by shershen08** [comment]
@kalidiagne do you maybe have a code demo of the problem, not the screenshot?

**Comment by kalidiagne** [comment]
hi @iamwill123 @shershen08 
I already see the message, i can replicate it and share it on codepen tomorrow.

Thanks for support!

**Comment by kalidiagne** [comment]
Hi @iamwill123  @shershen08 

I can't replicate it in JS Fiddle, i paste here my code.
I hope it will be comprensibile.


`
<template>
  <div id="blog-homepage">
    <page-header
      title="Blog"
      subtitle="Un modo semplice e comodo per essere informati in tempo reale sulle news della Federazione Italiana Triathlon, e non solo.">
    </page-header>
    <div class="section">
      <div class="block">
      </div>
      <div class="container">
        <el-tabs v-model="currentTab" @tab-click="test">
          <el-tab-pane label="init">
            <h3>First section</h3>
          </el-tab-pane>
          <el-tab-pane label="test">
            <h3>Test section</h3>
           <div class="row" v-masonry>
              <div v-masonry-title class="card-box col-md-4 col-sm-6" @click="readFeedPost(feed.feed)" v-for="feed in groupedFeed">
                <div class="card">                                            
                  <div class="content">
                    <el-tag type="primary" style="margin: 0 5px"> {{ feed.provider.title }} </el-tag>
                    <h4 class="title"><a href="#">{{ feed.feed.title }}</a></h4>
                    <p  v-if="feed.feed.title.length <= 70" class="description big" v-html="cutPostContent(feed.feed.content)"></p>
                    <small>
                      {{ feed.feed.pubDate | moment('DD/MM/YYYY') }}
                    </small>
                  </div>                                      
                </div> 
              </div>
              <div class="row" v-masonry>
              <div v-masonry-title class="card-box col-md-4 col-sm-6" @click="readFeedPost(feed.feed)" v-for="feed in groupedFeed">
                <div class="card">                                            
                  <div class="content">
                    <el-tag type="primary" style="margin: 0 5px"> {{ feed.provider.title }} </el-tag>
                    <h4 class="title"><a href="#">{{ feed.feed.title }}</a></h4>
                    <p  v-if="feed.feed.title.length <= 70" class="description big" v-html="cutPostContent(feed.feed.content)"></p>
                    <small>
                      {{ feed.feed.pubDate | moment('DD/MM/YYYY') }}
                    </small>
                  </div>                                      
                </div> 
              </div>
            </div>
            </div>
          </el-tab-pane>
        </el-tabs>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  const feedConverter = 'https://api.rss2json.com/v1/api.json?rss_url='
  const feedSourceList = [
    'http://www.fitri.it/archivio-news/news.feed?type=rss'
  ]
  export default {
    data () {
      return {
        currentTab: '',
        visibleFeedList: 'Seleziona feed',
        feedItems: [],
        feedProviders: [],
        feedFcz: [],
        postList: [],
        mediaList: [],
        currentNews: {},
        postLoaded: false,
        dialogNewsVisible: false,
        post: [
          '/static/img/header/run.jpg',
          '/static/img/header/header-default.jpg',
          '/static/img/header/bike.jpg',
          '/static/img/header/bike-team.jpg'
        ]
      }
    },
    computed: {
      groupedFeed () {
        var vm = this
        let feeds = []
        vm.feedItems.forEach(feed => {
          feed.items.forEach(singleFeed => {
            feeds.push({
              feed: singleFeed,
              provider: feed.feed
            })
          })
        })
        return this.$lodash.orderBy(feeds, ['feed.pubDate'], ['desc'])
      },
      filteredPost () {
        var vm = this
        let posts = []
        vm.postList.forEach(post => {
          posts.push(post)
        })
        return posts
      },
      isPostAviable () {
        return this.postLoaded && this.filteredPost.length
      }
    },
    mounted () {
      var vm = this
      feedSourceList.forEach(source => {
        vm.$http
          .get(`${feedConverter}${source}`)
          .then(res => {
            vm.feedItems.push(res.data)
          })
      })

      vm.$http
        .get(`http://localhost:8888/abapitalia/index.php/wp-json/wp/v2/media`)
        .then(res => {
          vm.mediaList = res.data
          console.log(vm.mediaList)
        })

      vm.$http
        .get('http://localhost:8888/abapitalia/index.php/wp-json/wp/v2/posts')
        .then(res => {
          vm.postList = res.data
          vm.postLoaded = true
        })
    },
    methods: {
      test () {
      },
      readBlogPost (post) {
        var vm = this
        setTimeout(() => {
          vm.$router.push({
            name: 'blog-post',
            params: {
              id: post.id,
              slug: post.slug
            }
          })
        }, 0)
      },
      readFeedPost (post) {
        var vm = this
        setTimeout(() => {
          vm.$router.push({
            name: 'blog-post',
            params: {
              id: 'feed',
              slug: post.title.replace(' ', '-')
            }
          })
        }, 0)
      },
      featuredMedia (mediaId) {
        var vm = this
        let currMedia = vm.mediaList.find(media => {
          if (media.id === mediaId) return media.guid.rendered
        })
        let returnVal = currMedia.guid.rendered || ''
        return returnVal
      },
      cutPostContent (postContent) {
        let htmlClean = postContent.replace(/<[^>]*>/g, '').slice(0, 180).concat('...')
        return htmlClean
      },
      readNews (news) {
        var vm = this
        vm.dialogNewsVisible = true
        vm.currentNews.title = news.title
        vm.currentNews.content = news.content
      },
      closeNewsModal () {
        var vm = this
        vm.dialogNewsVisible = false
        vm.currentNews = {}
      }
    }
  }
</script>
`

**Comment by iamwill123** [comment]
Hey @kalidiagne I'm looking at the jsfiddle but nothing is showing up, I actually created something I will share that handles RSS feeds similarly to how you have it but more componentized. I'm going to get the repo setup and then I'll link it. Meanwhile, the fiddle is not showing up but I do see a flicker of it briefly then it disappears.

**Comment by kalidiagne** [comment]
HI @iamwill123 thank you for your support!
I update the fiddle, now it's working, but the bug it's not replicable, everything work properly.
So i update my code with the fiddle code but error still present.
I share you a screen
 
<img width="714" alt="schermata 2017-09-19 alle 08 09 13" src="https://user-images.githubusercontent.com/20865711/30578154-c2cf7cee-9d12-11e7-8fc0-ff89b4e0e98d.png">

**Comment by shershen08** [comment]
@kalidiagne so does the issue still exist?

**Comment by iamwill123** [comment]
@kalidiagne Hey, here's the [repo](https://github.com/iamwill123/vue-masonry-starter-pack) for the starter pack, I'm not sure what the issue is on your side, but check it out. Heres the live [demo](https://vue-masonry-starter-pack.netlify.com/). It may point you in the right direction.

-Will

**Comment by kalidiagne** [comment]
@iamwill123 Hello, the issue is no longer present, i think it was caused by imported css.
Thank's to everybody for support!

**Comment by shershen08** [comment]
thanks for updating on this one @kalidiagne
