### ISSUE TITLE
'VueMasonryPlugin' was not found.

### ISSUE THREAD

**Issue by Topi99** [shershen08/vue-masonry#21]
When I run webpack I have a WARNING:

`export 'VueMasonryPlugin' was not found in './src/VueMasonry.vue'`.

Please, help :octocat:

**Comment by shershen08** [comment]
Well that's definitely smth wrong with your webpack setup I guess. Can you post your config here?

**Comment by Topi99** [comment]
```
module.exports = {
	entry: __dirname + '/src/index.js',
	output: {
		path: __dirname + '/dist',
		filename: 'bundle.js'
	},
	module: {
		loaders: [
			{test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
			{test: /\.css$/, exclude: /node_modules/, loader: 'style-loader!css-loader' },
			{test: /\.vue$/, loader: 'vue-loader'},
			{test: /\.html$/, loader: 'html-loader'}
		]
	},
	resolve: {
		alias: {
			vue: 'vue/dist/vue.js'
		}
	}
}
```

**Comment by shershen08** [comment]
hmm, I am not sure where's the problem here or in file where you use the vue-masonry plugin.
Can you try some standard solution, like one of those - https://github.com/vuejs-templates ?
