### ISSUE TITLE
How do you build the add button?

### ISSUE THREAD

**Issue by approached** [shershen08/vue-masonry#22]
https://shershen08.github.io/vue-plugins-demo-static/index.html#/masonry

How do you build the add button?

I tried the same but it look tearable by me.

**Comment by shershen08** [comment]
Hello @approached 
here is the small demo - https://jsfiddle.net/shershen08/qnfgv5vw/

basically it's those blocks do it:

```
//function to add new block filled with random text
 addBlock: function() {
  this.blocks.push({
  text:lipsum.generate(10)});
  },
```
```
// initial array
new Vue({
  el: '#app',
    data: {
      msg: 'Hello',
      showTextBlock: false,
      blocks: [{...
```
```
<!--template-->
 <div v-for="block in blocks">
  <div v-masonry-tile class="item-2">
    <p>{{block.text}}</p>
    </div>
  </div>
```

hope that helps

**Comment by approached** [comment]
Thank you for your comment. 
The main problem is, i add the item at first position with **unshift**. That looks not really good.

Demo Problem: 
https://jsfiddle.net/qnfgv5vw/4/
