### ISSUE TITLE
error export 'VueMasonryPlugin' was not found in './src/VueMasonry.vue'

### ISSUE THREAD

**Issue by charlzgod** [shershen08/vue-masonry#23]
Created a project on nuxt.js and such a connection error

**Comment by shershen08** [comment]
@charlzgod please provide more information. Ideally the repository link.

**Comment by pingshunhuangalex** [comment]
@shershen08 I also got the same error, and actually, I don't know how to use this tool after following the instructions on the repo. I load the original masonry in Webpack and it works fine, that shouldn't be the issue. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/17170199/28860585-8445baf2-77a0-11e7-81f1-158d834d6c9e.png)

**Comment by shershen08** [comment]
You guys right, I'll update the plugin a bt

**Comment by shershen08** [comment]
please install/update the latest version 0.10.5, should be all good now

https://www.npmjs.com/package/vue-masonry
