### ISSUE TITLE
Uglifier complains with `Unexpected token: operator (>)` in 0.10.5

### ISSUE THREAD

**Issue by patrickjahns** [shershen08/vue-masonry#24]
Removing the intermediate vue leads to problems with UglifyJs:

```
ERROR in js/index.js from UglifyJs
Unexpected token: operator (>) [./~/vue-masonry/src/masonry.plugin.js:19,0][js/index.js:75261,27]
```

Not sure how or if it can be fixed?

**Comment by shershen08** [comment]
can you try with https://github.com/shershen08/vue-masonry/blob/master/src/masonry.plugin.js#L19 like this ?
` const stringToBool = (val) => (val + '').toLowerCase() === 'true';`
I can't reproduce the setup to test right now, but I could roll the fix today

**Comment by patrickjahns** [comment]
I tried but it would still fail with the mentioned error (just different character place). I don't quite understand how the intermediate vue would not cause this issue -_-

**Comment by shershen08** [comment]
OK I'll check that today

**Comment by shershen08** [comment]
@patrickjahns can you check this repo i've cretaed with `vue-masonry` and adding `uglifyjs-webpack-plugin`
https://github.com/shershen08/vue-masonry-plugin-demo

And it seem to work fin for me

**Comment by patrickjahns** [comment]
will do as soon as I can get around provide feedback

**Comment by proov** [comment]
Hello guys !

I Have this issue too using [Nuxt.js](https://nuxtjs.org/) lastest `1.0.0-rc3`, Vue-Masonry `0.10.6` and Masonry `4.2.0`. I did exactly what they said in the nuxt.js documentation :

1. create `~plugins/vue-masonry.js` with this code inside:
``` js
import Vue from 'vue'
import VueMasonryPlugin from 'vue-masonry'

Vue.use(VueMasonryPlugin)
```

2. Reference the plugin in `nuxt.config.js`:
``` js
module.exports = {
  /*
  ** Plugins
  */
  plugins: ['~plugins/vue-masonry'],
  /*
  ** Other stuffs
  */
}
```

3. I put your little piece of code in a Vue Component `~components/Masonry.vue`
``` html
<template>
  <div v-masonry origin-left="false" transition-duration="0s" item-selector=".item">
    <div v-masonry-tile class="item">
      lol
    </div>
  </div>
</template>
```

results in : 

> ERROR in vendor.bundle.b0a0b374ac713a5680b0.js from UglifyJs
> Unexpected token: operator (>) [./node_modules/vue-masonry/src/masonry.plugin.js:19,0][vendor.bundle.b0a0b374ac713a5680b0.js:16836,26]

Any idea to how to fix this ? 🤔 

Thanks ✋

**Comment by shershen08** [comment]
@proov can you show how you included / configured the UglifyJS plugin?

**Comment by proov** [comment]
@shershen08 I dont know :( I'm using Nuxt.js right out the box, i installed it with `vue init nuxt/starter <project-name>`

However, i located `node_modules/nuxt/package.json` there is `"uglify-js": "^3.0.23"`, does it help you ?

**Comment by shershen08** [comment]
@patrickjahns any new on that one ?

**Comment by shershen08** [comment]
I've tried to investigate that error and seem that `Unexpected token: operator (>)` may occur commonly if you version of UglifyJS or your uglifyjs settings do not support ES6 features. 

With proper setting it should work fine. 
1) Check some of those links:
 - https://github.com/mishoo/UglifyJS2/issues/448
 - https://stackoverflow.com/questions/40367491/error-from-uglifyjs-syntaxerror-unexpected-token-operator
 - https://github.com/JeffreyWay/laravel-mix/issues/790

2) Take a look at that sample repo with Vue + Vue-masonry + UglifyJS I've created - https://github.com/shershen08/vue-masonry-plugin-demo
[uglifyjs-webpack-plugin](https://www.npmjs.com/package/uglifyjs-webpack-plugin) uses https://www.npmjs.com/package/uglify-es btw

I am open for a feedback if you say it's a bug in vue-masonry file. Please feel free to reopen if you have further considerations. But for now  I see it as matter of configuration of your project, not a bug of vue-masonry plugin.

**Comment by patrickjahns** [comment]
Sorry for the delayed response - thank you very much for checking - I will see that we implement your solution and eget back to you
