### ISSUE TITLE
masonry does not work when transition-group added on list items 

### ISSUE THREAD

**Issue by azhard4int** [shershen08/vue-masonry#27]
Hi

I am trying to implement transition-group on the items but masonry does not work if we do that.

Here is the code

```
<div class="videos_list clear" v-masonry transition-duration="0.4s" item-selector=".vid-box">

     <transition-group name="fade" tag="div">
                <div class=" col-md-4  vid-box content-box pinto" :key="post" v-masonry-tile v-for="(post, index) in getPosts">
                    <div class="box-inner"> Content Here</div>
                </div>
     </transition-group>
</div>
```

Is there any workaround for this? As we need to apply transition when we remove some item from the list.

**Comment by pingshunhuangalex** [comment]
The reason for this is because your CSS set for transition in transition group is conflicting with vue-masonry's transition. You need to set the `transition-duration=0` first (assume you already have `transition: all .4s` set in your CSS for your `fade`)

**Comment by azhard4int** [comment]
@pingshunhuangalex I can set that to transition-duration=0 but that would not solve the problem of masonry as it is no working when we use it.

**Comment by pingshunhuangalex** [comment]
Then it must be your fade css is not written properly. It's either use vue-masonry's transition or your transition. If you set `transition-duration=0` and transition is not working then it must be your css

**Comment by azhard4int** [comment]
@pingshunhuangalex it is not about transition, masonry plugin does not work at all. All the items are set with their default styling.

**Comment by pingshunhuangalex** [comment]
That's weird. Is vue-masonry working on other cases? Or like doesn't work even it's not in a transition group?

**Comment by azhard4int** [comment]
when we remove the transition-group, everything works perfectly.

Though, we have handled this case using jQuery to apply the transition when the user remove the item.

**Comment by pingshunhuangalex** [comment]
Mmm, not sure then. It's a bit nasty using jQuery to take things out as things should be data-driven in Vue.

Maybe @shershen08 can shed some light on this.

**Comment by azhard4int** [comment]
You are right, jQuery is not the appropriate solution at first place, but there are certain scenarios where you might need to use the jQuery when your project is of mid-large scale like Trello etc.

**Comment by shershen08** [comment]
@azhard4int I didn't check myself the effects of `transition-group` on masonry/vue-masonry markup. 
**masonry** library itself has its own animation effects so I was not planning to interfere with it.
If you have a improvement that may make it work in vue-masonry - feel free to submit a PR.

**Comment by shershen08** [comment]
Any proposal on this one @azhard4int  ?
If you have new findings please feel free to reopen.
