### ISSUE TITLE
[Vue warn]: Failed to resolve directive: masonry-tile

### ISSUE THREAD

**Issue by andreliem** [shershen08/vue-masonry#28]
I've been trying to get vue-masonry to work in various Vuejs projects. I've tried blank projects from the CLI (webpack, pwa, and nuxt) and it seems like it's always failing with this error

`[Vue warn]: Failed to resolve directive: masonry-tile`
`Failed to resolve directive: masonry`

I've followed the steps verbatim and for some reason vue js cannot use the directive...

Also, I tried the demo `vue-masonry-demo` and it's also giving me the same issues.

Any idea? Can't seem to figure this one out!

**Comment by iamwill123** [comment]
Hey @andreliem I had the same problem, I ended up installing "vue-masonry": "^0.10.5" version and it's working for me. Try npm install vue-masonry@0.10.5. 
Best,
Will

**Comment by andreliem** [comment]
Thanks @iamwill123, that solved my problem as well. @shershen08, any ideas on what might be going on with the latest version? Thanks for the plugin btw, very handy.

**Comment by pingshunhuangalex** [comment]
https://github.com/shershen08/vue-masonry/issues/26
