### ISSUE TITLE
Listen to Masonry events

### ISSUE THREAD

**Issue by rico** [shershen08/vue-masonry#3]
Sorry, me again - is it somehow possible to listen to the events of the underlying Masonry instance (e.g. `layoutComplete`)?

**Comment by shershen08** [comment]
Thanks for the question!
Currently there are no masonry events (like those http://masonry.desandro.com/events.html, right ?) broadcasted outside of the plugin.

**Comment by rico** [comment]
Thanks for your quick answer - and the package, of course.

Yes exactly those events :-) No problem, I'll find another way.

**Comment by shershen08** [comment]
Btw @rico here's the improvement in the library that you were requesting for - https://github.com/shershen08/vue-masonry/issues/6

**Comment by rico** [comment]
@shershen08 many thanks for getting it done and the information!

**Comment by Guillaume69** [comment]
Hi, sorry but i don't see how your solution fix the problem. You globaly expose redrawVueMasonry to the Vue instance, but in which way i can listen to 'layoutComplete' event ? Thank you !
