### ISSUE TITLE
Add some loading experience before all pictures are loaded

### ISSUE THREAD

**Issue by dib258** [shershen08/vue-masonry#33]
Hi there,

Thanks for this package that encapsulate masonry for VueJs.

I'm facing a little problem where I want to make some loading gif for each image or for all pictures loaded by masonry. And in the package I see you use imageLoaded and you emit events when it's done.

Do you think of a way to either listen to this event in my own Vue instance or a way to easily make loading experience before all the pictures are loaded correctly ?

Thanks in advance for you time !

**Comment by shershen08** [comment]
Internally there a `imageLoaded` lib used for defining this stage when all content images are in place already.

Maybe listening for the event `vuemasonry.imageLoaded` may help.

Let me know is if it worked out

**Comment by dib258** [comment]
That's something I tried to do.

`<div v-masonry-tile class="item" v-for="(item, index) in blocks" v-on:vuemasonry.imageLoaded="test">
   <div>
       <img :src="item.url" :alt="item.caption" class="img-responsive">
   </div>
</div>`

Where I created a test method with some `console.log('test')` but nothing happens...

And in the pugin the Events are handled in another Vue instance apparently. Maybe I can't reach this event or maybe I'm not listening right to the event's name. (which his weird to have a dot in it since normally on a v-on the dot indicate that there's is a Event Modifiers, So don't know if this is what it is interfering)

**Comment by shershen08** [comment]
I see @dib258 
I'll try to invest some time into this coming days and get back to you.
If you have some specific proposal - please feel free to describe the implementation here or create a PR

**Comment by dib258** [comment]
Thank you @shershen08 !
I'll try to find a solution also if something comes to my mind !

**Comment by shershen08** [comment]
thanks for updating on this one @dib258

**Comment by zArubaru** [comment]
@dib258, Disclaimer: I'm quite new at Vue.js.

But I had a similar situation, though I'm revealing images after they've been loaded via get/JSON.

I'll give you part commented sections and part production code, as my situation was a bit different.

I made a component:

```
<template>
  <div class="item"
       v-masonry-tile>
     <img :src="item.img">
  </div>
</template>

<script>
  export default {
    name: 'masonry-tile',
    props: ['item'],
    created() {
      // @todo emit event here, at this point the image has been loaded as far as I can tell
    },
  };
</script>
```

and the file the component is used in:

```
<template>
  <div v-masonry
       transition-duration="0"
       item-selector=".item">
    <masonry-tile v-for="(item, index) in tiles"
                  :item="item"
                  :key="index">
    </masonry-tile>
  </div>
</template>

<script>
  import MasonryTile from '@/components/MasonryTile';

  export default {
    name: 'MasonryTest',
    components: {
      MasonryTile,
    },
    data() {
      return {
        tiles: [],
      };
    },
    methods: {
      loadImages() {
        // @todo, add images, wait for each masonry-tile component to emit that
        // it is ready and then show the whole container hiding the loading image
      },
    },
  };
</script>
```

Please ask if you need a more complete example.
