### ISSUE TITLE
Strange error when deploy to Heroku, using with Meteor + Vue

### ISSUE THREAD

**Issue by ducdev** [shershen08/vue-masonry#35]
![image](https://user-images.githubusercontent.com/3524016/30662349-fca509de-9e70-11e7-82a6-6ae4f97c7231.png)
Hello, it's working well on development (with devDependencies) but not on production bundling.

**Comment by shershen08** [comment]
Hello @ducdev 
I am not sure I can give you some help with this case - without a code to reproduce the case it's hard to say in which piece of code the problem lies. I would recommend to thoughtfully debug the code to allocate the error.
Please update me if you will have clearer pointers on the vue-masonry plugin code.

**Comment by ducdev** [comment]
I think the issue is related to vue-masonry-plugin.js as it's displayed in the error log. But when I located the file, it's minified and obfuscated.

**Comment by ducdev** [comment]
And when Meteor bundle app, it continue to minify it once more. I think the file will be broken. Not sure.

**Comment by shershen08** [comment]
I would recommend to enable source maps that see the exact line in the minifyed JS file

**Comment by ducdev** [comment]
This is what I can see.
![image](https://user-images.githubusercontent.com/3524016/30664811-28979db0-9e79-11e7-8301-978802508273.png)

**Comment by ducdev** [comment]
How is it going @shershen08 did you locate the issue ?

**Comment by shershen08** [comment]
@ducdev sorry no, I though you're trying to do that

**Comment by ducdev** [comment]
Do you have any idea why the variables were naming like that ?

**Comment by shershen08** [comment]
it's a typical when JS file is minimised/uglified. Can you try to disable it (https://stackoverflow.com/questions/23841145/running-meteor-js-in-production-without-combining-and-minifying-js-files) and see where's the problem then?

**Comment by ducdev** [comment]
Hi @shershen08 it seems the issue is caused by default `standard-minifier-js` package of Meteor, and I've changed it to a customized package and the issue is solved. Thanks for your time on creating `vue-masonry` and supporting me.

**Comment by shershen08** [comment]
OK, great to hear that it was solved!
