### ISSUE TITLE
Temporary duplicate when adding a new element in the Masonry Grid

### ISSUE THREAD

**Issue by Itemshopp** [shershen08/vue-masonry#36]
Hi all,

I'm creating a Masonry grid and the elements are pushed to an array from a json. Everything's fine until the moment I prepend a new element to this array. I use a polling system that listens every 10 seconds and grab new elements in a json. Then prepends thoses images at the beginning of the Masonry Grid.  

I tried adding one new image. And when it's prepended to the array and pops in masonry this new picture is a copy of the second picture [ which was the first picture before the popping image ] during 0,5 second before becoming its own.

Two things here are disturbing : 
- The flash when the first image becomes the second
- If the first image is bigger than the second one, the second one takes its place as normal but it will create a void under it with no redraw. Even calling ,this.$redrawMasonry(); won't do anything...

The particular thing is, when I PUSH an element into the masonry array with a push, everything's ok, the image appears clearly with it's proper size. But when I UNSHIFT that same element into the masonry array, a new tile is created as a double of the one on its right and after 0,5 seconds becomes its own with that void under it.

I don't know if I detailed the situation enough, let me know if you want further explanations.

Thanks a lot for your help !

**Comment by shershen08** [comment]
hello @Itemshopp thanks for this a really detailed description. 

What I could recomend to check, at least the part:

> The particular thing is, when I PUSH an element into the masonry array with a push, everything's ok, the image appears clearly with it's proper size. But when I UNSHIFT that same 

maybe that has to do with reactivity in Vue(see http://jsfiddle.net/xb5h545w/1/ and https://medium.com/js-dojo/reactivity-in-vue-js-and-its-pitfalls-de07a29c9407), and using `Vue.set` may help

**Comment by Itemshopp** [comment]
Thanks for your answer, but your jsfiddle is unreadable. I added Vue.js as framework but it still doesn't display anything. Do you know what I can do to make it work ?

**Comment by Itemshopp** [comment]
I figured out something thanks to your article.
The Vue.set function can be useful when you modify an object after Vue has rendered.

In my case, here, prepending or appending is the same action. It should be problematic either ways but in the appending phase everything works well but the prepending phase goes wrong.
( as I said : When prepending, it duplicates the first tile a the top left masonry grid, so we have a duplicated image without any redraw )

What I think, maybe suppose is a better chosen word : 
- When prepending the object in the beginning of the array bound with masonry, I think masonry doesn't "reloadItems" and "layout" like it should be when we append.

I hope you understand wat I'm trying to say

**Comment by shershen08** [comment]
Thanks for the efforts @Itemshopp 
To have some useful result improvements we should have / create a test case with demo in code.
Do you have any solution for that one or an idea how things could be fixed ?

**Comment by hayaato** [comment]
I saw that vue-masonry did a Vue.nextTick() to call his redraw function, I had the same problem.
I did 
```javascript
    Vue.nextTick(() => {
        this.$redrawVueMasonry()
    })
```
And it solves my problem
Hope it will help :)

**Comment by shershen08** [comment]
@Itemshopp since there was no feedback on this from you and @hayaato posted a what helps to work around I am closing this one.
