### ISSUE TITLE
How to use Fitwidth

### ISSUE THREAD

**Issue by trickstival** [shershen08/vue-masonry#38]
I didn't understand how doest fitWidth works. Can I center the masonry items with it?

**Comment by shershen08** [comment]
You can see the difference in the demo here: https://jsfiddle.net/shershen08/qnfgv5vw/7/
This prop is not about the items inside, it's 

> Sets the width of the container to fit the available number of columns

You also may want to take a look at the original lib `fitWidth` option description: https://masonry.desandro.com/options.html#fitwidth

Hope that helps
