### ISSUE TITLE
Why are Events bound to a new Vue instance? This confuses vue-devtools.

### ISSUE THREAD

**Issue by sandrooco** [shershen08/vue-masonry#43]
Related to [#39](https://github.com/shershen08/vue-masonry/issues/39):

The code looks like this:
````
const Events = new Vue({})
...
VueMasonryPlugin.install = function (Vue, options) {
 ...
}
````
Why is `Events` a new Vue instance? This makes vue-devtools malfunction because it thinks the `vue-masonry` instance is the main one...

**Comment by shershen08** [comment]
It was done using this proposed approach:
https://vuejs.org/v2/guide/components.html#Non-Parent-Child-Communication

**Comment by shershen08** [comment]
is there a better proposal with that @sandrooco ?
feel free to open or create a PR

**Comment by sandrooco** [comment]
@shershen08 No probably not - there's something wrong with the package though. I don't yet know what..
