### ISSUE TITLE
Images overlaping

### ISSUE THREAD

**Issue by Licoti** [shershen08/vue-masonry#44]
Hi there,

I have problem of image overlaping, (like this issue https://github.com/shershen08/vue-masonry/issues/9, but i have no plugin) it's because items change sizes at the same time as the images loads

I saw this :
```
  mounted: function(){
    this.$redrawVueMasonry();
  },
```
But there is always a problem, because this doesn't matter when items change size when the page is loading :(

It's possible to fix the problem to use the on progress method of masonry (imagesLoaded - https://masonry.desandro.com/layout.html#imagesloaded) ?

```
imagesLoaded( grid ).on( 'progress', function() {
  // layout Masonry after each image loads
  msnry.layout();
});
```

Thanks for help

**Comment by shershen08** [comment]
Hello @Licoti 
current version uses the second approach from this https://masonry.desandro.com/layout.html#imagesloaded
it `initialize Masonry after all images have been loaded.`

I'll try to experiment with proposed option coming days and will provide an update

**Comment by Licoti** [comment]
Ok !
For information, i have installed Vue-imageloaded (https://github.com/David-Desmaisons/Vue.ImagesLoaded) and it's good.

```
    <div v-images-loaded:on.progress="imageProgress">
      <div v-masonry transition-duration="0.3s" item-selector=".album_class--item" column-width=".grid-sizer" percentPosition="true">
...
      </div>
    </div>
```

```
    methods: {
      imageProgress(instance, image ) {
        const result = image.isLoaded ? 'loaded' : 'broken';
        console.log('image is ' + result + ' for ' + image.img.src);
      }
    }
```

**Comment by shershen08** [comment]
yes, that's maybe a smart to replace the original ImagesLoaded with the Vue wrapped one

**Comment by frutality** [comment]
@Licoti `imageProgress` method in your case working as expected? In my case it's fired only once, when all images loaded. This results in images overlapping until all images are loaded. Even more, only `instance` is defined. `image` is `undefined` all the time.

**Comment by frutality** [comment]
Hi @catonalake 

Unfortunately, no. I ended up with own solution. In my case, width and height of images are known, so no need to wait for image loaded events.

**Comment by rotemrevivo91** [comment]
I have the same problem. My solution is to wait for a promise for 850ms (smallest interval that worked for me) and then redraw the masonry layout. The time delay is so small that is literally unnoticeable.

```javascript
mounted(){
	this.onLoad()
},
methods:{
	async onLoad(){
		await this.sleep(850)
		this.$redrawVueMasonry()
	},
	sleep(ms){
  		return new Promise(resolve => setTimeout(resolve, ms))
	}
}
```

**Comment by gengchen528** [comment]
how to use imagesLoaded in this project. i  find `imagesloaded` had been import in this project. but there is no demo to show how to use it.  can you help me? thank you

**Comment by chakflying** [comment]
Came up with an alternative solution for if you know how many images you are loading:

*template*
```vue
<div v-masonry="'my_thing'" transition-duration="1s">
      <div v-masonry-tile>
          <img :src="item"
            @load="imageLoaded"
          />
      </div>
</div>
```

*script*
```javascript
data() {
  return {
      imagesloaded: 0
    }
  },
methods: {
    imageLoaded() {
      this.imagesloaded += 1
      if (this.imagesloaded === this.items.length) {
        this.$redrawVueMasonry('my_thing')
      }
    }
  }
```

I don't know why 'my_thing' has to be wrapped as a string in both places, but it doesn't seem to work otherwise.

**Comment by sonnb** [comment]
Just in case someone needs. If you use v-image, you can listen to the load event and redraw the layout everytime a new image is loaded.

```vue
<v-img
          :src="item.url_m"
          :lazy-src="item.url_m"
          @load="$redrawVueMasonry('containerId')"
          class="white--text align-end"
        >
```

**Comment by shershen08** [comment]
closing for now
