### ISSUE TITLE
Latest version not working with nuxt

### ISSUE THREAD

**Issue by camilodelvasto** [shershen08/vue-masonry#46]
I'm having an issue with the most recent version and nuxt RC-11: https://github.com/nuxt/nuxt.js/issues/1359
The previous version doesn't produce the error. Here a glitch: https://glitch.com/edit/#!/hanging-angle

*Thanks for the great work!

**Comment by shershen08** [comment]
Sorry @camilodelvasto I dont' see the any log or code on thise addres, only 
```
# Fetching Project ...
Securely store app secrets and config in .env
```
Can you use http://jsfiddle.net or https://codepen.io/ or paste in here to share code ?

**Comment by camilodelvasto** [comment]
@shershen08 Glitch is great for this, much better than codepen/jsfiddle as you can add node modules.

To reproduce the issue: check the activity logs, displaying: `"export 'default' (imported as 'VueMasonryPlugin') was not found in 'vue-masonry'`

To remove the error: change the vue-masonry version in package.json to `0.10.5` —That removes the error.

**Comment by shershen08** [comment]
I've managed to make the glitch.com work - it was a proxy issue on my side.

And the right way to use is 
`import {VueMasonryPlugin} from 'vue-masonry'`
mind the brackets, as stated in the README. Use [Import a single export from a module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
