### ISSUE TITLE
Is it possible to use this plug-in as script distribution?

### ISSUE THREAD

**Issue by sreecodeslayer** [shershen08/vue-masonry#47]
How can I use this plug-in without actually configuring npm to serve the files?
Like, can I use this the way vue-router and vue-resource are used, by simply fetching via a script tag?

The reason why I ask is, coz I normally develop in Python environment, and all my backend servers are in Flask.

**Comment by shershen08** [comment]
not at the moment. but it's a nice to have feature, I'll check if that's possible to add asap

**Comment by sreecodeslayer** [comment]
I see, anyways, I got it to work by building it by changing the webpack build conf as :

```
const libraryName = 'VueMasonry';
const outputFile = libraryName + '-script.js';

```
And then after building this one with webpack, I was able to use the file from dist in script tag, as 

`Vue.use(VueMasonry.VueMasonryPlugin)`
Not quite sure if that's the way to do, but it works with the `import` statements :thinking:

**Comment by shershen08** [comment]
Yes, @sreecodeslayer that's the totally legit approach I would be using too. But my point was that current pre-built vue-masonry doesn't have it.

**Comment by sreecodeslayer** [comment]
ah, gotcha, thanks :wink:

**Comment by shershen08** [comment]
Now as from `0.11.3` it's fully available solution, check README
