### ISSUE TITLE
Vue-masonry default-render distorted, corrects on modifying viewport size, using with vuetify

### ISSUE THREAD

**Issue by sidjainn** [shershen08/vue-masonry#49]
<img width="1280" alt="screen shot 2017-12-28 at 10 14 16 am" src="https://user-images.githubusercontent.com/16212304/34400499-00453f52-ebb8-11e7-9287-f56f641857eb.png">

**Comment by shershen08** [comment]
Can you please provide the code sample, which properties of Vue-masonry plugin were used?

That also may have to deal with imagesLoaded settings, referenced here https://github.com/shershen08/vue-masonry/issues/44

**Comment by shershen08** [comment]
Closing due to being outdated and inactive
