### ISSUE TITLE
Two mistakes

### ISSUE THREAD

**Issue by kotuck** [shershen08/vue-masonry#53]
Hello, i like your plugin. But i found two mistakes.
1). Please replace all value "const" to "var". It's not supported in old browsers.
2). Don't import Vue in your plugin, because bundle will have 2 copy of Vue (from their app and your plugin).

**Comment by shershen08** [comment]
Thanks for your input @kotuck 
But referencing your second point 

>  Don't import Vue in your plugin

I am using it in the plugin code, because I make use of the following features of Vue instance

- Events = new Vue({})
- Vue.nextTick
- Vue.directive

**Comment by shershen08** [comment]
Thanks for the input on second point, it was referenced for several times already, so finally fixed it.
