### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by Nisthar** [shershen08/vue-masonry#58]
I am trying to use it in nuxtjs. I am looking for a package that supports SSR.

Does this support SSR?

**Comment by shershen08** [comment]
Sorry for late reply @Nisthar 
In the readme there's a section on how to configure vue-masonry with Nuxt - https://github.com/shershen08/vue-masonry#nuxt-ssr-implimentation

Did you try that?

**Comment by rosnaib11** [comment]
Better if this have SSR support
