### ISSUE TITLE
Showing hidden text, need to reload Masonry

### ISSUE THREAD

**Issue by ishigami** [shershen08/vue-masonry#6]
Hi shershen08, how are you?

I need a little help yours. I have a tile where there is a short text with a button to show the complete text inside this tile. Is there a method to call the reloadItens() function or something to do the masonry recalculate the position of the tiles?

Tks a lot.

**Comment by shershen08** [comment]
Hi @ishigami 
I see your problem. I'll get back to you today on that.

**Comment by ishigami** [comment]
Tks a lot shershen08.

**Comment by shershen08** [comment]
I've tried to have a simplified demo here: https://jsfiddle.net/shershen08/g1Lkee4q/

Basically this code can be run when masonry redraw is needed:
 
```
 var evt = document.createEvent('UIEvents');
 evt.initUIEvent('resize', true, false, window, 0);
 window.dispatchEvent(evt); 

```
but as to me it woks once and then until a real resize happens it doesn't work. trying to figure pout why.

**Comment by ishigami** [comment]
Hi shershen08 the same behavior happens to me. I'm trying to find some alternative for this. I'll be in touch if I have some news.

Tks again. You're great.

**Comment by shershen08** [comment]
for now I first want to separate if it's a masonry itself or vue-js introduced behaviour

**Comment by shershen08** [comment]
the solution is simple, have a [vue plugin](https://vuejs.org/v2/guide/plugins.html) wrap the whole thing. then you can have a global Vue method to perform redrawing

Here's a demo implementation - https://jsfiddle.net/shershen08/6po2gwn2/

I'll create new version of vue-masonry as a **vue plugin** this weekend

Closing for now If you're OK

**Comment by ishigami** [comment]
Tks a lot shershen08. I'll apply this later.
