### ISSUE TITLE
Cards Stacking on top of each other

### ISSUE THREAD

**Issue by Nfinished** [shershen08/vue-masonry#60]
Haven't been able to reliably reproduce it yet, but in these two examples cards are occasionally being positioned on top of each other. Anyone else experiencing this?

![screen shot 2018-05-07 at 11 27 15 am](https://user-images.githubusercontent.com/1719791/39712477-2f3a0b22-51f1-11e8-8a8d-c2f25c9b381b.png)

![screenshot_20180507_122101](https://user-images.githubusercontent.com/1719791/39712515-4c5ae5fa-51f1-11e8-9d89-c412f6a9b7bf.png)

In this one, it looks like what should be the first card in the list is being shifted down and to the right, under another card.

**Comment by shershen08** [comment]
may that be smth related to #9  ?

**Comment by Nfinished** [comment]
That's an interesting suggestion, those lines of text each start off as a single line before they're populated. 

Might calling `$redrawVueMasonry()` after the text has rendered fix the problem, or would that be too late?

**Comment by Nfinished** [comment]
Doesn't work.

**Comment by Nfinished** [comment]
@shershen08 After some more testing it doesn't seem to be related to height recalculations, I could reproduce this 8 times out of 10 with tiles that had a static height.

**Comment by shershen08** [comment]
8/10 is good enough, now it would be nice have a files that I could run to see the issue

**Comment by Nfinished** [comment]
It looks like the root cause may have been a computed function masonry was relying on was recomputing too rapidly (even with a forced redraw), made sure it only computed once and everything seems to be running smoothly.
