### ISSUE TITLE
[Request] masonry exact versions

### ISSUE THREAD

**Issue by panstromek** [shershen08/vue-masonry#62]
Could you please specify masonry and imagesloaded versions better in package.json? "latest" modifier is not safe and makes irreproducible builds on different machines. Latest version number with ^ is enough imo.

For some reason npm on my co-worker's machine completely removes those dependencies from lockfile and produce incorrect installation.

**Comment by panstromek** [comment]
Also "masonry" dependency is useless, I guess? It's different library, not related to masonry-layout

**Comment by shershen08** [comment]
Good point, will look into this shortly

**Comment by shershen08** [comment]
fixed in https://github.com/shershen08/vue-masonry/commit/77446ed2ee4a7bb75a48f6f47350ea0c3b76171e

**Comment by panstromek** [comment]
Thanks. Immediately noticed, npm started installing correctly. 

Not sure what was wrong though, same on my new computer, npm just removed imagesLoaded dependency when I was trying to run npm install.. Not sure it is a bug in npm or intended behaviour, if I should report it or what...

**Comment by shershen08** [comment]
imagesLoaded should stay since it is in package.json.
