### ISSUE TITLE
Conditional activation

### ISSUE THREAD

**Issue by luminous8** [shershen08/vue-masonry#67]
Hi Guys,

Is there a way to activate v-masonry only when a value is equal to true?
Something like this `v-bind:valueToTest="v-masonry"`?

Thanks

**Comment by shershen08** [comment]
@luminous8 nothing like this is present at the moment.
Can you give more details on use case of this?

**Comment by luminous8** [comment]
@shershen08 Because I have to views : a squared grid and a pinterest-like grid and I don't want masonry on the squared-one. I fixed it with a v-if / v-else but that add more code lines

**Comment by shershen08** [comment]
Yes I'd suppose v-if or v-show could be enough in this case.
Feel free to create a PR if you like.
Closing for now
