### ISSUE TITLE
How to I change the type of transition (not just duration)?

### ISSUE THREAD

**Issue by nicroto** [shershen08/vue-masonry#69]
Sorry for the basic question, but I don't see any docs (here or on the desandro repo) about the type of transition to use. Is there any way to change that?
Thanks.

**Comment by shershen08** [comment]
Since this is a Vue.js wrapper on top of the desandro's library it doesn't add new options to what;'s in the original one: https://masonry.desandro.com/options.html.

TL;DR
You, can't do that
