### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import only for this package

### ISSUE THREAD

**Issue by patrickbolle** [shershen08/vue-masonry#7]
Hi there, Vue 2.0 from the webpack template (Vue CLI).

Just tried to install this package but as soon as I put it in my Vue component or main.js file, my site stops loading and I get:
`Uncaught SyntaxError: Unexpected token import 
`
on this statement - 
`import {masonry, masonryTile} from 'vue-masonry';
`
I've tried installing other npm packages/vue plugins/directives etc, and they all work totally fine.

Any ideas here?

Thanks!

**Comment by shershen08** [comment]
@patrickbolle I'll try to reproduce on clean Vue 2.x install and get back to you asap

**Comment by shershen08** [comment]
I've just checked the clean install of vue-cli with webpack template and install of simple  `"vue-masonry": "0.9.5"` on it - it all works fine for me. I couldn't reproduce your error. 

Can you check your setup, because `Uncaught SyntaxError: Unexpected token import`` is a generic error is your ES6 code is not being properly by your loader. 

Do you use vue-cli webpack template?

Please provide more details so that I could try to help you out.

**Comment by patrickbolle** [comment]
Weird! 
Yeah I'm using the vue-cli webpack template. 
Maybe I should make an issue on that repo instead. 

Any other info I could give to you?

**Comment by shershen08** [comment]
Do you have a large codebase on that project? 
If not maybe you could zip it and let the take a look?

**Comment by patrickbolle** [comment]
I've got it hosted on Gitlab if you'd like to take a look at the repo (it's private, so you'll need an account)

**Comment by shershen08** [comment]
I've checked your repo.
You're using webpack 1.x and  "vue-loader": "^9.4.0".
I am pretty sure this is the problem in configuring the setup, not the plugin itself.
        
Try taking a clean vue-cli project that uses webpack 2.x - https://github.com/vuejs-templates/webpack. Plugin works fine with those.

**Comment by shershen08** [comment]
Hey, @patrickbolle . did you try to check on that one?

**Comment by patrickbolle** [comment]
Hey. Super sorry, been really busy with freelance clients this week. I should have some time today or tomorrow to try this out. You think I could just upgrade webpack and vue loader 'gracefully' rather than redoing the project from scratch?

Cheers! Appreciate your help.

**Comment by shershen08** [comment]
well since **webpack and vue-loader** are just build tooling, not the libraries used in your project code I don't see a reason why you need to change your code. 

Maybe other loaders will need to be upgraded as well as the **webpack config file** - https://webpack.js.org/guides/migrating/

**Comment by patrickbolle** [comment]
Upgraded :) works great now, thanks!!

**Comment by shershen08** [comment]
Nice to hear! Good!

**Comment by patrickbolle** [comment]
Hey @shershen08 quick question, sort of unrelated.

I'm using this code - 
```
 <div v-masonry transition-duration="0.1s" class="row">
            <div v-masonry-tile class="col-lg-4" v-for="(category, index) in categories">
                <CategoryComponent :category="category"></CategoryComponent> 
            </div>
 </div>
```
The category component is just a list of items (varying number of items).

I've got vue masonry working, but it isn't working properly with the height of each CategoryComponent (which is dynamic).

It ends up looking like this - 
![Masonry Issue](https://cloud.githubusercontent.com/assets/11012317/24325436/548114b6-116f-11e7-9a05-0d227fd132f9.png)

It's not respecting the height of each list, and everything is being absolute positioned on top of each other.

Any ideas here?
