### ISSUE TITLE
some mobilBrower would warning this——use const in strict mode

### ISSUE THREAD

**Issue by shrimpbighead** [shershen08/vue-masonry#71]
this warning makes the page not rendered successfully. how to use the babel-polyfill to transform es6 into es5 .

**Comment by shershen08** [comment]
@shrimpbighead  not very clear message. 
Please describe what use case you have (build system, node, vue.js versions) ?
What exactly fails in your setup?

**Comment by shershen08** [comment]
closing due to **inactivity** 
@shrimpbighead  feel free to up reopen if you have updates
