### ISSUE TITLE
No (re)order happens until an element selected by column-width appears.

### ISSUE THREAD

**Issue by nicroto** [shershen08/vue-masonry#75]
The issue with that is - if I have different size items and for a while only the other type of items get pulled with AJAX and added, they get squished together over one another, until an item selected by column-width shows up. Only then suddenly the container gets sized up.

**Comment by nicroto** [comment]
Can't find a workaround... Would it be possible to set the size of the minimal item programatically to the masonry instance? (instead of it trying to guess it from the dom element)

**Comment by shershen08** [comment]
fixed in` 0.11.6`
