### ISSUE TITLE
Android 4.4 - Use of const in strict mode.

### ISSUE THREAD

**Issue by padinko** [shershen08/vue-masonry#78]
On Android 4.4 there is error in console and app not working:
`Uncaught SyntaxError: Use of const in strict mode.`

I think `main` in `package.json` should not point on src file, because webpack is not babel vendors.

for now I use 
`import { VueMasonryPlugin } from 'vue-masonry/dist/vue-masonry-plugin-umd'`
and it resolve my problem

**Comment by shershen08** [comment]
see https://github.com/shershen08/vue-masonry#usage-with-build-tools block

`import {VueMasonryPlugin} from 'vue-masonry';`

is exactly the right way to do it.

Feel free to reopen if you still have a problem
