### ISSUE TITLE
Responsive layout not working

### ISSUE THREAD

**Issue by Peretz30** [shershen08/vue-masonry#79]
I am trying to implement something like this:
![image](https://user-images.githubusercontent.com/27721091/47260799-dc576f00-d4ca-11e8-91c5-f3417e506fdc.png)
With this:
```
columnWidth: 20%
percentPosition: true
```
And something wrong happening. Please, check https://jsfiddle.net/6g5bx97m/3/

**Comment by shershen08** [comment]
Your setup is not fully correct: in your 
`<div v-masonry percent-position column-width=".grid-sizer" transition-duration="0.3s" item-selector=".item" `
you didn't set the selector for the actual masonry single block - your  `item-selector=".item"` while there's no .item elements.
You should have it smth like this:
```
<div v-masonry percent-position column-width=".grid-sizer" transition-duration="0.3s" item-selector=".single-item" 
...
<div v-masonry-tile class="single-item" 
...
</div>
</div>
```

**Comment by shershen08** [comment]
Take a look at the demo https://shershen08.github.io/vue-plugins-demo-static/index.html#/masonry
hope that helps
