### ISSUE TITLE
pluginWideMasonryRef is not a function

### ISSUE THREAD

**Issue by rickbolton** [shershen08/vue-masonry#8]
I've just tried to add `Vue.redrawVueMasonry()` when my items change and I'm receiving the error pluginWideMasonryRef is not a function.

I tested changing the function within the masonry.plugin.js to something like below which worked fine. Not sure whether I'm implementing it incorrectly or whether this an issue? 

```
Vue.redrawVueMasonry = function () {
    Events.$emit(EVENT_ADD)
};
```

**Comment by shershen08** [comment]
Oh, you totally right, I was changing and forgot to commit the last change
I'll update the package tonight

**Comment by rickbolton** [comment]
Thanks for the quick reply. That's great thanks!

**Comment by shershen08** [comment]
Commited npm `version 0.10.1`
