### ISSUE TITLE
Getting [Vue warn]: Failed to resolve directive: masonry

### ISSUE THREAD

**Issue by jluterek** [shershen08/vue-masonry#81]
So on my application, this happen on first load.  Then if I navigate away using vue-router and back to page, it will properly load masonry and display.

I tested it with the JSFiddle example - https://jsfiddle.net/jericopulvera/wq07brjs and this also throws the error.

I get this behavior in Firefox 63.0, Chrome Version 70.0.3538.77, and Edge all with Windows 10.

> vue.js:597 [Vue warn]: Failed to resolve directive: masonry
> 
> (found in <Anonymous>)
> warn @ vue.js:597
> resolveAsset @ vue.js:1518
> normalizeDirectives$1 @ vue.js:6266
> _update @ vue.js:6191
> updateDirectives @ vue.js:6183
> invokeCreateHooks @ vue.js:5685
> createElm @ vue.js:5573
> createChildren @ vue.js:5669
> createElm @ vue.js:5571
> patch @ vue.js:6117
> Vue._update @ vue.js:2660
> updateComponent @ vue.js:2788
> get @ vue.js:3140
> Watcher @ vue.js:3129
> mountComponent @ vue.js:2795
> Vue.$mount @ vue.js:8527
> Vue.$mount @ vue.js:10926
> Vue._init @ vue.js:4627
> Vue @ vue.js:4716
> window.onload @ (index):34
> load (async)
> (anonymous) @ (index):32

Any thoughts?

**Comment by jluterek** [comment]
I should mention that on the demo - https://shershen08.github.io/vue-plugins-demo-static/index.html#/masonry

I get

> Uncaught ReferenceError: Masonry is not defined

>     at inserted (build.js:9)
>     at Nt (build.js:3)
>     at Object.l [as insert] (build.js:3)
>     at v (build.js:3)
>     at Ie.__patch__ (build.js:3)
>     at Ie.e._update (build.js:2)
>     at Ie.<anonymous> (build.js:2)
>     at ui.get (build.js:3)
>     at new ui (build.js:3)
>     at Ie.e._mount (build.js:2)
> inserted @ build.js:9
> Nt @ build.js:3
> l @ build.js:3
> v @ build.js:3
> (anonymous) @ build.js:3
> e._update @ build.js:2
> (anonymous) @ build.js:2
> ui.get @ build.js:3
> ui @ build.js:3
> e._mount @ build.js:2
> Ie.$mount @ build.js:4
> (anonymous) @ build.js:9
> t @ build.js:1
> (anonymous) @ build.js:54
> t @ build.js:1
> (anonymous) @ build.js:1
> (anonymous) @ build.js:1

If I hard-refresh (shift-f5) it will then work properly.

**Comment by shershen08** [comment]
I would advise to check #59 if that's something similar to your case?

Also about error on demo page - really no idea, nothing like this reported previously. Some problems with network connectivity/firewall/installed extesions maybe?

**Comment by jluterek** [comment]
Sorry, for bothering you with this.  I really appreciate the great work on this plugin.

If anyone else if finding this, be sure to specify your:

` Vue.use(VueMasonryPlugin);`

Before creating your vue app and mounting it.
