### ISSUE TITLE
images overlaping

### ISSUE THREAD

**Issue by AliChaudhry8** [shershen08/vue-masonry#82]
Hey there,
I Have a wrapper on my page with a closing sidebar. When images appear it looks good. but when i close the sidebar images overlap , move from right and overlap on left side. I am not resizing the window just closing the sidebar which actually increase the width of other half screen that's causes images overlaping.

**Comment by shershen08** [comment]
Hey, @AliChaudhry8  could you check if that #44 is relevant ?

**Comment by shershen08** [comment]
Any update on that one @AliChaudhry8 ?

**Comment by shershen08** [comment]
closing due to no reproducible demo and inactivity
