### ISSUE TITLE
Can I import vue-masonry only in my component?

### ISSUE THREAD

**Issue by jtpdev** [shershen08/vue-masonry#84]
I want to import vue-masonry in my component, but I doesn't find nothing in documentation.

It's possible? And how make it?

**Comment by shershen08** [comment]
Since `vue-masonry` is initialised as a plugin it has to be included in root of the app as a plugin - https://vuejs.org/v2/guide/plugins.html#Using-a-Plugin

**Comment by shershen08** [comment]
So it's not possible.
If you provide a use case - we can think of possible approaches.

**Comment by zonique2k** [comment]
We would like to use vue-masonry in a spfx webpart in sharepoint. That means we don't control the entire page, just a small part of it. 
Other webparts (from other vendors) on the same page might also use vue-masonry, maybe in another version which might not be compatible with the one we use (maybe a future new major version).
That why we always use local registered components
