### ISSUE TITLE
Importing Masonry instead of using the CDN

### ISSUE THREAD

**Issue by CrashyBang** [shershen08/vue-masonry#85]
Curious how I can get this working by importing Masonry like so:
```
import Masonry from 'masonry-layout';
```
Instead of using the CDN and having it global, anyway to pass `VueMasonryPlugin` the `Masonry` instance?

**Comment by shershen08** [comment]
I'm not quite sure what you're trying to achieve 
currently masonry is imported as a module within the plugin code - https://github.com/shershen08/vue-masonry/blob/master/package.json#L16

**Comment by shershen08** [comment]
closing for now since now activity
@CrashyBang feel free to reopen or ping me on twitter
