### ISSUE TITLE
Tile height doesn't recalculate on content height change

### ISSUE THREAD

**Issue by Nfinished** [shershen08/vue-masonry#86]
If a tile's height, or the height of its children, is changed dynamically masonry won't assign it a new height and it'll either overlap with another tile or create a space. Is this a missing use-case or am I doing something wrong?

**Comment by shershen08** [comment]
Thanks for the input @Nfinished 
Does the original masonry (without a vue plugin) do that ?

did you try calling ` this.$redrawVueMasonry()` ?

**Comment by Nfinished** [comment]
That's a good point, I hadn't realized this was just a straight wrapper for a javascript library.

`$redrawVueMasonry()` wouldn't work in my situation because the content being resized is in slots and there's nothing to watch efficiently.

**Comment by shershen08** [comment]
$redrawVueMasonry() should be able to call from any component - in your case the ones in the slots that are actually being resized

**Comment by shershen08** [comment]
any updated on this one @Nfinished 
if you were able to fix it please share

**Comment by shershen08** [comment]
**closing** for now due to inactivity
feel free to reopen or share your findings

**Comment by mGGk-fr** [comment]
Hello,

I re-open this as i encounter the same problem.
Context: 
One of my element inside my masonry layout may expand it's height.
Basically, i display a div depending on a v-if condition.

here's a sample of the code that i use :
```
showEditor(){
    this.showEditor = true;
    this.$redrawVueMasonry('myId');
}
````
But it does nothing.
I've tried to call it after a tick

```
showEditor(){
    this.showEditor = true;
    this.$nextTick(() => {
        this.$redrawVueMasonry('myId');
    });
}
```

BTW calling the redraw method after adding or removing an element works like a charm.
Thanks for your feedback
