### ISSUE TITLE
Why the items are not centering inside the <v-layout> Vuetify

### ISSUE THREAD

**Issue by MuhaddiMu** [shershen08/vue-masonry#92]
Here is my code which is not working as expected. 

```
<v-row class="justify-center">
      <v-layout
        v-masonry
        fit-width="true"
        transition-duration="1s"
        item-selector=".item"
        class="masonry-container"
        justify-center
      >
        <v-flex
          align="center"
          justify="center"
          class="item ma-2 align-center justify-center"
          v-masonry-tile
          v-for="Idea in Ideas"
          :key="Idea.DocID"
          xs12
          md4
        >
          <v-card hover width="320" class="mx-auto">
            <v-card-Title class="title">
              {{ Idea.Title}}
              <v-spacer></v-spacer>
              <v-tooltip right>
                <template v-slot:activator="{ on }">
                  <v-icon v-on="on" v-if="Idea.Completed" class="green--text" small>done_all</v-icon>
                  <v-icon v-on="on" v-else class="orange--text text--lighten-2" small>update</v-icon>
                </template>
                <span>{{Idea.Completed ? "Completed" : "Pending"}}</span>
              </v-tooltip>
            </v-card-Title>
            <v-card-text>{{ Idea.Description }}</v-card-text>

            <v-card-actions class="caption grey--text text--darken-3">
              Added on: {{ Idea.Added }}
              <br />
              Visibility: {{ Idea.Visibility }}
              <v-spacer></v-spacer>
              <v-menu nudge-top="6" top offset-x>
                <template v-slot:activator="{ on }">
                  <v-btn icon v-on="on">
                    <v-icon>more_vert</v-icon>
                  </v-btn>
                </template>
                <v-list>
                  <v-list-item v-for="(Option, i) in Options" :key="i">
                    <v-list-item-title>{{ Option.Title }}</v-list-item-title>
                  </v-list-item>
                </v-list>
              </v-menu>
            </v-card-actions>
          </v-card>
        </v-flex>
      </v-layout>
    </v-row>
```

Current Output: 
![Current Output. Items are aligned to the left side.](https://user-images.githubusercontent.com/26611847/65262007-df1b7380-db22-11e9-8fe4-b9af3f0d7971.png)

Expected To Be(Like):
![Centering all of the card items AKA masonry content](https://user-images.githubusercontent.com/26611847/65261995-dcb91980-db22-11e9-8c7b-dab040363b44.png)

I'm using Vuetify 2.0.0

Please feel free to check my [GitHub](https://github.com/MuhaddiMu/Idea-ReVue/commit/00f8a591d47ab05321650533bc5af91a6bbdc79b) that needs to fix that problem 

Any help would be highly appreciated. 

Thanks
Muhaddis

**Comment by shershen08** [comment]
For such issues where there's no clear JS error, but more of the CSS misbehaving it would be nice to see the jsfiddle/codepen with demo - I sorry I don't have time to clone and install the app to debug it.

An idea to check - are you maybe using fitwidth with percentage width of children?
as the https://masonry.desandro.com/options.html#fitwidth docs say:
> fitWidth: true does not work with element sizing with percentage width. Either columnWidth needs to be set to a fixed size, like columnWidth: 120, or items need to have a fixed size in pixels, like width: 120px. Otherwise, the container and item widths will collapse on one another.

**Comment by MuhaddiMu** [comment]
Thank you for your response. Well, that's was basically my layout issue. 
I was not using `fill-height` in my container
