### ISSUE TITLE
Vue-masonry not working in Internet Explorer 11

### ISSUE THREAD

**Issue by hyperst8** [shershen08/vue-masonry#93]
Hi,
I have setup and used vue-masonry in my Nuxt project. Everything works fine in browsers like Chrome and Firefox. It doesn't work in Internet Explorer 11. Do you know how to solve this?
It gives a error message:

```
Script1014: Invalid character
vendors.app.js (69040, 21)
```

Screenshot:
![image](https://user-images.githubusercontent.com/19534642/66991548-98407f80-f0c8-11e9-9a41-92e9039049fc.png)

Thanks in advance

**Comment by shershen08** [comment]
Hey,  which build tool you are using?
did you try to include vue-masonry from files that are ES5-compatible  - https://github.com/shershen08/vue-masonry/tree/master/dist

**Comment by austriker27** [comment]
> 
> 
> Hey, @hyperst8 which build tool you are using?
> did you try to include vue-masonry from files that are ES5-compatible - https://github.com/shershen08/vue-masonry/tree/master/dist

How do I include those tools? I'm using the vue CLI (with webpack) and getting an error in IE11. 

Error: 
![image](https://user-images.githubusercontent.com/14855925/68149166-3ec2b800-fef2-11e9-85e9-006132ee676e.png)

Error in file:
![image](https://user-images.githubusercontent.com/14855925/68149194-4c783d80-fef2-11e9-9967-ddd90cd064a9.png)

I can open a new issue if desired. I found that apparently IE doesnt use `eval` via this [post](https://stackoverflow.com/questions/1050840/how-can-i-get-this-eval-call-to-work-in-ie). 

I am using babel to transpire my dependencies like this one.

**Comment by shershen08** [comment]
So does the above config  solve your problem @hyperst8 ?
I that is an issue for your project, but considering the specific case (IE11 in 2019) maybe a copying a dependency in your codebase and transpiling it in a specific way so that ie11 can handle this is workable solution.

**Comment by jhlee8804** [comment]
v0.11.7 working now. But v0.11.8 is not working on IE11.

**Comment by shershen08** [comment]
@jhlee8804 the change bw 0.11.7 and 0.11.8 are
- use more ES6 syntax
- add all the masonryId logic

@hyperst8 can you confirm that using 0.11.7 solves the problem? then we could act accordingly - update README, create a PR to fix that inconsistency

**Comment by dantuck** [comment]
@shershen08 it is confirmed that changing to 0.11.7 does solve the problem.

**Comment by fabis94** [comment]
It looks like this package isn't properly transpiled on build, because the build includes code that can't be understood by IE11.

**Comment by shershen08** [comment]
please switch to @ 0.11.7 @fabis94 
will close for now, feel free to reopen

**Comment by seagoj** [comment]
Are we certain that v0.11.7 will work in IE11? I have tried to downgrade and I'm still seeing the issue.
