### ISSUE TITLE
Example using Tailwind CSS

### ISSUE THREAD

**Issue by rogervila** [shershen08/vue-masonry#96]
Hello,

I have created an example using a [Tailwind CSS card example](https://tailwindcss.com/components/cards/#app)

https://jsbin.com/zafegay/edit?html,output

The link might be added to the readme.

Thank you.

**Comment by shershen08** [comment]
Looks nice! Could you please create a PR modifying README.md ?

**Comment by rogervila** [comment]
Yes, thank you :)
