### ISSUE TITLE
Multiple instances on one page - if one is destroyed, both are destroyed

### ISSUE THREAD

**Issue by kirkbushell** [shershen08/vue-masonry#99]
I have a shared component that renders a masonry directive. On one of my pages, I have 2 of them. Essentially what I do, is add items to one, and update the other at the same time. 

If the one I'm adding items to is emptied, I have logic to remove the masonry rendering - all good.

However, it seems to also destroy the masonry instance on the page (all the items suddenly go to the far left).

I've looked at using containerIds and also the destroy-delay found here #95 however, none of these seem to resolve the problem (tbh whenever I use containerIds the entire system goes belly-up). The issue appears to be that calling masonry.destroy() is destroying all instances.

**Comment by shershen08** [comment]
here we call a destroy - https://github.com/shershen08/vue-masonry/commit/f6271d139343ed382890d07fc0be9cf2416e8c1b#diff-6515fb01dcdfe1d3d96674797d6492bbab4bf782f8e9151fe76e67a17e3da9e7R75

but instance is created on a specific element - https://github.com/shershen08/vue-masonry/blob/master/src/masonry.plugin.js#L58
and also the destroy event has an id suffix in it:

```
${EVENT_DESTROY}__${masonryId}
```

do you maybe have a demo repo or a codepen sandbox to reproduce the issue ?

**Comment by shershen08** [comment]
closing as no response
